name: Publish to GitHub pages and NPM

on:
    workflow_call:
        inputs:
            cache_sha:
                type: string
                required: true

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Get dist files
              uses: actions/cache@v4
              with:
                  path: dist
                  key: dist-${{ inputs.cache_sha }}

            - name: Get docsite files
              id: get-docs-cache
              uses: actions/cache@v4
              with:
                path: docs
                key: docs-${{ inputs.cache_sha }}

            - name: Add docs folder to dist
              if: steps.get-docs-cache.outputs.cache-hit == 'true'
              run: mv docs dist

            - name: Deploy to GitHub Pages 🚀
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: dist
                  target-folder: ${{ github.head_ref || github.ref_name }}
                  single-commit: true

            - name: Publish to NPM
              if: github.repository == 'milespetrov/ramp4-pcar4' && startsWith(github.ref, 'refs/tags/v')
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - uses: actions/github-script@v6
              name: Post link to demo for PR's
              if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Your demo site is ready! 🚀

                        Main: https://${{github.repository_owner}}.github.io/ramp4-pcar4/${{github.head_ref}}/
                        Catalogue: https://${{github.repository_owner}}.github.io/ramp4-pcar4/${{github.head_ref}}/demos/index-all.html
                        Samples: https://${{github.repository_owner}}.github.io/ramp4-pcar4/${{github.head_ref}}/demos/index-samples.html`
                      })
