name: Main Build Workflow

on:
    pull_request_target:
        types: [opened, synchronize, reopened]

    push:
        branches:
            - 'main'
            - 'qa'
        tags:
            - v**

jobs:
    build-docs:
        name: Build for docsite
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
        uses: ./.github/workflows/build-docs.yml
        with:
            cache_sha: ${{ format('{0}-{1}', github.ref_name, github.event.pull_request.head.sha || github.sha) }}

    build:
        name: Merge dev & prod into a bundle
        needs: [build-docs]
        if: |
            always() &&
            (needs.build-docs.result == 'success' || needs.build-docs.result == 'skipped')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
                  repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

            - uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: 'npm'

            - name: Build the files!
              run: |
                  npm ci
                  npm run build
              env:
                  NODE_OPTIONS: '--max-old-space-size=8192'

            - name: Cache dist files
              uses: actions/cache@v4
              with:
                  path: dist
                  key: dist-${{ format('{0}-{1}', github.ref_name, github.event.pull_request.head.sha || github.sha) }}

            - name: Get docsite files
              uses: actions/cache@v4
              if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
              with:
                  path: docs
                  key: docs-${{ format('{0}-{1}', github.ref_name, github.event.pull_request.head.sha || github.sha) }}

            - name: Add docs folder to dist
              if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
              run: mv docs dist

    deploy-pages:
        needs: [build]
        if: always() && (needs.build.result == 'success')
        name: Deploy the files
        uses: ./.github/workflows/pages.yml
        with:
            cache_sha: ${{ format('{0}-{1}', github.ref_name, github.event.pull_request.head.sha || github.sha) }}

    deploy-npm:
        needs: [build]
        name: Deploy build file to npm
        uses: ./.github/workflows/npm-publish.yml
        with:
            cache_sha: ${{ format('{0}-{1}', github.ref_name, github.event.pull_request.head.sha || github.sha) }}
