name: Publish to npm

on:
    workflow_call:
        inputs:
            cache_sha:
                type: string
                required: true

jobs:
    main:
        name: NPM Publish
        runs-on: ubuntu-latest
        if: github.repository == 'milespetrov/ramp4-pcar4' && startsWith(github.ref, 'refs/tags/v')

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  registry-url: 'https://registry.npmjs.org'

            - name: Grab the build files from the cache
              uses: actions/cache@v4
              with:
                  path: dist
                  key: dist-${{ inputs.cache_sha }}

            - name: Update version in package.json
              run: |
                  TAG_VERSION=${GITHUB_REF#refs/tags/v}
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
                    npm version --allow-same-version --no-git-tag-version $TAG_VERSION
                    echo "::warning::Tag version ($TAG_VERSION) did not match package.json version ($PACKAGE_VERSION). Updated package.json to $TAG_VERSION."
                  else
                    echo "::info::Tag version ($TAG_VERSION) matches package.json version ($PACKAGE_VERSION)."
                  fi

            - name: Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
