on:
    pull_request:
        types: [opened, synchronize]

jobs:
    pr-status-checks:
        name: PR Status Checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: latest
                  cache: 'npm'

            - name: Try to restore node_modules folder from cache
              id: cache-node-modules
              uses: actions/cache@v4
              with:
                  path: ./node_modules
                  key: npm-${{ hashFiles('./package-lock.json') }}

            - name: Otherwise install npm dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci

            - uses: milespetrov/status-checks@main
              id: pr-checks
              with:
                  gh-token: ${{ secrets.GITHUB_TOKEN }}
                  ts-command: 'npm run ts:check'
                  lint-command: 'npm run lint:check'
                  format-command: 'npm run format:check'
